name: hello-world
on: push #whatever push on this repo, this workflow will trigger
jobs:
  my-job:
    runs-on: ubuntu-latest #github has same VM and containers
    steps:
      - name: my-step
        run: echo "Hello World!"
